name: Cachix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#accentor-web
      - run: nix build -L --no-link .#accentor-api
      - run: nix build -L --no-link .#accentor-api.env
      - run: nix eval --json ".#accentor-web.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
      - run: nix eval --json ".#accentor-api.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
      - run: nix eval --json ".#accentor-api.env.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
