name: Cachix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: "(-source$|\\.tgz$|\\.gem$|-modules-|-offline$)"
      - run: nix build -L --no-link .#accentor-web
      - run: nix build -L --no-link .#accentor-api
      - run: nix build -L --no-link .#accentor-api.env
