name: Nix
on: [push]

jobs:
  nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg:
          - accentor-web
          - accentor-api
          - accentor-api-env
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Build ${{ matrix.pkg }}
      run: nix build .#${{ matrix.pkg }}
